// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BinaBvNfawQZzDPESb8xy3y25RogtJI',
    appId: '1:105283954198:web:b229a60bcb3104eb083737',
    messagingSenderId: '105283954198',
    projectId: 'e-commerce-app-54cb4',
    authDomain: 'e-commerce-app-54cb4.firebaseapp.com',
    storageBucket: 'e-commerce-app-54cb4.appspot.com',
    measurementId: 'G-9VVH72FEK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Zlr-VVY99Cg1PYzqYloLEOmc4f8rEWI',
    appId: '1:105283954198:android:806a8f00843629ed083737',
    messagingSenderId: '105283954198',
    projectId: 'e-commerce-app-54cb4',
    storageBucket: 'e-commerce-app-54cb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcIVqqWTHGv4Cgs2P4EwA2eBmFkjpyiM',
    appId: '1:105283954198:ios:20bb3f5f516166a3083737',
    messagingSenderId: '105283954198',
    projectId: 'e-commerce-app-54cb4',
    storageBucket: 'e-commerce-app-54cb4.appspot.com',
    iosClientId: '105283954198-0s68sav05fgvhh2dl38051unh2phlmdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjcIVqqWTHGv4Cgs2P4EwA2eBmFkjpyiM',
    appId: '1:105283954198:ios:4f3c5c581cd10ed5083737',
    messagingSenderId: '105283954198',
    projectId: 'e-commerce-app-54cb4',
    storageBucket: 'e-commerce-app-54cb4.appspot.com',
    iosClientId: '105283954198-0lgb248kscs5gv9ro9septv3hkntamfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
